import { WinningTeam } from "./types";

export const WINNING_TEAMS: WinningTeam[] = [
  {
    id: "t1",
    name: "Sand Offense",
    player: "Wolfe Glick",
    placement: "1st Place",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 282, name: "Gardevoir" },
    ],
  },
  {
    id: "t2",
    name: "Trick Room Control",
    player: "Eduardo Cunha",
    placement: "2nd Place",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 36, name: "Clefable" },
      { pokemonId: 780, name: "Drampa" },
    ],
  },
  {
    id: "t3",
    name: "Rain Offense",
    player: "James Baek",
    placement: "1st Place",
    event: "Champions Showdown Week 1",
    pokemon: [
      { pokemonId: 186, name: "Politoed" },
      { pokemonId: 9, name: "Blastoise" },
      { pokemonId: 130, name: "Gyarados" },
      { pokemonId: 448, name: "Lucario" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 547, name: "Whimsicott" },
    ],
  },
  {
    id: "t4",
    name: "Sun Hyper Offense",
    player: "Paul Ruiz",
    placement: "1st Place",
    event: "Champions Series Invitational #2",
    pokemon: [
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 6, name: "Charizard" },
      { pokemonId: 952, name: "Scovillain" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
    ],
  },
  {
    id: "t5",
    name: "Balance Core",
    player: "Nils Dunlop",
    placement: "2nd Place",
    event: "Champions Series Invitational #2",
    pokemon: [
      { pokemonId: 376, name: "Metagross" },
      { pokemonId: 149, name: "Dragonite" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 681, name: "Aegislash" },
    ],
  },
  {
    id: "t6",
    name: "Dondozo Rush",
    player: "Alex Gomez",
    placement: "1st Place",
    event: "Champions Showdown Week 2",
    pokemon: [
      { pokemonId: 977, name: "Dondozo" },
      { pokemonId: 10009, name: "Wash Rotom" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 887, name: "Dragapult" },
    ],
  },
  {
    id: "t7",
    name: "Mega Lucario Offense",
    player: "Lee Sang-hyeok",
    placement: "1st Place",
    event: "Champions Korea Qualifier",
    pokemon: [
      { pokemonId: 448, name: "Lucario" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t8",
    name: "Mega Metagross Core",
    player: "Toler Webb",
    placement: "Top 4",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 376, name: "Metagross" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 547, name: "Whimsicott" },
    ],
  },
  {
    id: "t9",
    name: "Hard Trick Room",
    player: "Melvin Keh",
    placement: "Top 4",
    event: "Champions Series Invitational #2",
    pokemon: [
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 765, name: "Oranguru" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 740, name: "Crabominable" },
      { pokemonId: 531, name: "Audino" },
    ],
  },
  {
    id: "t10",
    name: "Tailwind Hyper Offense",
    player: "Alessio Yuri",
    placement: "1st Place",
    event: "Champions Europe Qualifier",
    pokemon: [
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 149, name: "Dragonite" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 681, name: "Aegislash" },
    ],
  },
  {
    id: "t11",
    name: "Mega Charizard Y Sun",
    player: "Ryota Otsubo",
    placement: "1st Place",
    event: "Champions Japan Qualifier",
    pokemon: [
      { pokemonId: 6, name: "Charizard" },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 212, name: "Scizor" },
    ],
  },
  {
    id: "t12",
    name: "Mega Dragonite Bulky",
    player: "Aaron Zheng",
    placement: "2nd Place",
    event: "Champions Showdown Week 1",
    pokemon: [
      { pokemonId: 149, name: "Dragonite" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 376, name: "Metagross" },
    ],
  },
  {
    id: "t13",
    name: "Mega Kangaskhan Rush",
    player: "Sejun Park",
    placement: "2nd Place",
    event: "Champions Korea Qualifier",
    pokemon: [
      { pokemonId: 115, name: "Kangaskhan" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 472, name: "Gliscor" },
      { pokemonId: 748, name: "Toxapex" },
      { pokemonId: 908, name: "Meowscarada" },
    ],
  },
  {
    id: "t14",
    name: "Sand Balance",
    player: "Gabriel Agati",
    placement: "2nd Place",
    event: "Champions Europe Qualifier",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 478, name: "Froslass" },
    ],
  },
  {
    id: "t15",
    name: "Mega Gyarados Setup",
    player: "Jon Hu",
    placement: "Top 4",
    event: "Champions Showdown Week 2",
    pokemon: [
      { pokemonId: 130, name: "Gyarados" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 681, name: "Aegislash" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "t16",
    name: "Mega Scizor Pivot",
    player: "Rachel Annand",
    placement: "Top 4",
    event: "Champions Showdown Week 1",
    pokemon: [
      { pokemonId: 212, name: "Scizor" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 36, name: "Clefable" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
    ],
  },
  {
    id: "t17",
    name: "Greninja Offense",
    player: "Simone Sanvito",
    placement: "Top 8",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 376, name: "Metagross" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 130, name: "Gyarados" },
    ],
  },
  {
    id: "t18",
    name: "Glimmora Lead Offense",
    player: "Eric Rios",
    placement: "Top 8",
    event: "Champions Series Invitational #2",
    pokemon: [
      { pokemonId: 970, name: "Glimmora" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 478, name: "Froslass" },
    ],
  },
  {
    id: "t19",
    name: "Mega Altaria Fairy",
    player: "Tommy Cooleen",
    placement: "Top 8",
    event: "Champions Showdown Week 2",
    pokemon: [
      { pokemonId: 334, name: "Altaria" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 681, name: "Aegislash" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 908, name: "Meowscarada" },
    ],
  },
  {
    id: "t20",
    name: "Rain Semi-Room",
    player: "Luca Calore",
    placement: "Top 8",
    event: "Champions Europe Qualifier",
    pokemon: [
      { pokemonId: 186, name: "Politoed" },
      { pokemonId: 130, name: "Gyarados" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 478, name: "Froslass" },
    ],
  },
  {
    id: "t21",
    name: "Mega Houndoom Dark",
    player: "Marcus Wong",
    placement: "Top 8",
    event: "Champions Japan Qualifier",
    pokemon: [
      { pokemonId: 229, name: "Houndoom" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 282, name: "Gardevoir" },
    ],
  },
  {
    id: "t22",
    name: "Mega Heracross Trick Room",
    player: "Marco Silva",
    placement: "Top 8",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 214, name: "Heracross" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 36, name: "Clefable" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "t23",
    name: "Mega Gengar Trap",
    player: "Yusei Aoki",
    placement: "2nd Place",
    event: "Champions Japan Qualifier",
    pokemon: [
      { pokemonId: 94, name: "Gengar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 681, name: "Aegislash" },
    ],
  },
  {
    id: "t24",
    name: "Raichu Pin Offense",
    player: "Daniel Nolan",
    placement: "Top 4",
    event: "Champions Europe Qualifier",
    pokemon: [
      { pokemonId: 26, name: "Raichu" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t25",
    name: "Mega Absol Anti-Meta",
    player: "Flavio Del Pidio",
    placement: "Top 4",
    event: "Champions Korea Qualifier",
    pokemon: [
      { pokemonId: 359, name: "Absol" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 748, name: "Toxapex" },
    ],
  },
  {
    id: "t26",
    name: "Aurora Veil Offense",
    player: "Haruka Tanaka",
    placement: "1st Place",
    event: "Champions Snow Invitational",
    pokemon: [
      { pokemonId: 10103, name: "Alolan Ninetales" },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t27",
    name: "Electric Terrain Rush",
    player: "Jordan Blake",
    placement: "1st Place",
    event: "Champions Circuit Week 5",
    pokemon: [
      { pokemonId: 10100, name: "Alolan Raichu" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 887, name: "Dragapult" },
    ],
  },
  {
    id: "t28",
    name: "Rotom Control",
    player: "Sofia Chen",
    placement: "Top 4",
    event: "Champions Regionals Summer",
    pokemon: [
      { pokemonId: 10008, name: "Heat Rotom" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 376, name: "Metagross" },
    ],
  },
  {
    id: "t29",
    name: "Hisuian Chaos",
    player: "Kai Nakamura",
    placement: "2nd Place",
    event: "Champions Legends Cup",
    pokemon: [
      { pokemonId: 10340, name: "Hisuian Zoroark" },
      { pokemonId: 10336, name: "Hisuian Samurott" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 448, name: "Lucario" },
    ],
  },
  {
    id: "t30",
    name: "Decidueye Fighting Spirit",
    player: "Marcus Williams",
    placement: "1st Place",
    event: "Champions Open Series 4",
    pokemon: [
      { pokemonId: 10341, name: "Hisuian Decidueye" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 478, name: "Froslass" },
    ],
  },
  {
    id: "t31",
    name: "Mega Victreebel Sun",
    player: "Isabella Torres",
    placement: "Top 4",
    event: "Champions Latin Cup",
    pokemon: [
      { pokemonId: 71, name: "Victreebel" },
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t32",
    name: "Mega Steelix Sand",
    player: "Erik Johansson",
    placement: "2nd Place",
    event: "Champions Nordic Series",
    pokemon: [
      { pokemonId: 208, name: "Steelix" },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 887, name: "Dragapult" },
    ],
  },
  {
    id: "t33",
    name: "Rotom Wash Balance",
    player: "Lisa Park",
    placement: "1st Place",
    event: "Champions Online Series 7",
    pokemon: [
      { pokemonId: 10009, name: "Wash Rotom" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "t34",
    name: "Mow Rotom Grass Core",
    player: "David Kim",
    placement: "Top 4",
    event: "Champions Pacific Qualifier",
    pokemon: [
      { pokemonId: 10012, name: "Mow Rotom" },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 376, name: "Metagross" },
    ],
  },
  {
    id: "t35",
    name: "Zoroark Illusion Tricks",
    player: "Nina Costa",
    placement: "1st Place",
    event: "Champions Showdown Week 8",
    pokemon: [
      { pokemonId: 10340, name: "Hisuian Zoroark" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "t36",
    name: "Fan Rotom Speed Control",
    player: "Tyler Adams",
    placement: "Top 8",
    event: "Champions US Nationals",
    pokemon: [
      { pokemonId: 10011, name: "Fan Rotom" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t37",
    name: "Frost Rotom Hail Hybrid",
    player: "Yuki Sato",
    placement: "2nd Place",
    event: "Champions Japan Qualifier",
    pokemon: [
      { pokemonId: 10010, name: "Frost Rotom" },
      { pokemonId: 10103, name: "Alolan Ninetales" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 376, name: "Metagross" },
      { pokemonId: 282, name: "Gardevoir" },
    ],
  },
  {
    id: "t38",
    name: "Samurott Edge Setter",
    player: "Carlos Mendez",
    placement: "1st Place",
    event: "Champions Latin Invitational",
    pokemon: [
      { pokemonId: 10336, name: "Hisuian Samurott" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
];

/**
 * Lookup: returns all winning teams that include a given Pokémon ID.
 */
export function getTeamsForPokemon(pokemonId: number): WinningTeam[] {
  return WINNING_TEAMS.filter((team) =>
    team.pokemon.some((p) => p.pokemonId === pokemonId)
  );
}
