import { WinningTeam } from "./types";

export const WINNING_TEAMS: WinningTeam[] = [
  {
    id: "t1",
    name: "Sand Offense",
    player: "Wolfe Glick",
    placement: "1st Place",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 282, name: "Gardevoir" },
    ],
  },
  {
    id: "t2",
    name: "Trick Room Control",
    player: "Eduardo Cunha",
    placement: "2nd Place",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 36, name: "Clefable" },
      { pokemonId: 780, name: "Drampa" },
    ],
  },
  {
    id: "t3",
    name: "Rain Offense",
    player: "James Baek",
    placement: "1st Place",
    event: "Champions Showdown Week 1",
    pokemon: [
      { pokemonId: 186, name: "Politoed" },
      { pokemonId: 9, name: "Blastoise" },
      { pokemonId: 130, name: "Gyarados" },
      { pokemonId: 448, name: "Lucario" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 547, name: "Whimsicott" },
    ],
  },
  {
    id: "t4",
    name: "Sun Hyper Offense",
    player: "Paul Ruiz",
    placement: "1st Place",
    event: "Champions Series Invitational #2",
    pokemon: [
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 6, name: "Charizard" },
      { pokemonId: 952, name: "Scovillain" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
    ],
  },
  {
    id: "t5",
    name: "Balance Core",
    player: "Nils Dunlop",
    placement: "2nd Place",
    event: "Champions Series Invitational #2",
    pokemon: [
      { pokemonId: 376, name: "Metagross" },
      { pokemonId: 149, name: "Dragonite" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 681, name: "Aegislash" },
    ],
  },
  {
    id: "t6",
    name: "Dondozo Rush",
    player: "Alex Gomez",
    placement: "1st Place",
    event: "Champions Showdown Week 2",
    pokemon: [
      { pokemonId: 977, name: "Dondozo" },
      { pokemonId: 10009, name: "Wash Rotom" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 887, name: "Dragapult" },
    ],
  },
  {
    id: "t7",
    name: "Mega Lucario Offense",
    player: "Lee Sang-hyeok",
    placement: "1st Place",
    event: "Champions Korea Qualifier",
    pokemon: [
      { pokemonId: 448, name: "Lucario" , isMega: true},
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t8",
    name: "Mega Metagross Core",
    player: "Toler Webb",
    placement: "Top 4",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 376, name: "Metagross" , isMega: true},
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 547, name: "Whimsicott" },
    ],
  },
  {
    id: "t9",
    name: "Hard Trick Room",
    player: "Melvin Keh",
    placement: "Top 4",
    event: "Champions Series Invitational #2",
    pokemon: [
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 765, name: "Oranguru" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 740, name: "Crabominable" },
      { pokemonId: 531, name: "Audino" },
    ],
  },
  {
    id: "t10",
    name: "Tailwind Hyper Offense",
    player: "Alessio Yuri",
    placement: "1st Place",
    event: "Champions Europe Qualifier",
    pokemon: [
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 149, name: "Dragonite" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 681, name: "Aegislash" },
    ],
  },
  {
    id: "t11",
    name: "Mega Charizard Y Sun",
    player: "Ryota Otsubo",
    placement: "1st Place",
    event: "Champions Japan Qualifier",
    pokemon: [
      { pokemonId: 6, name: "Charizard" , isMega: true, megaFormIndex: 1},
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 212, name: "Scizor" },
    ],
  },
  {
    id: "t12",
    name: "Mega Dragonite Bulky",
    player: "Aaron Zheng",
    placement: "2nd Place",
    event: "Champions Showdown Week 1",
    pokemon: [
      { pokemonId: 149, name: "Dragonite" , isMega: true},
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 376, name: "Metagross" },
    ],
  },
  {
    id: "t13",
    name: "Mega Kangaskhan Rush",
    player: "Sejun Park",
    placement: "2nd Place",
    event: "Champions Korea Qualifier",
    pokemon: [
      { pokemonId: 115, name: "Kangaskhan" , isMega: true},
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 472, name: "Gliscor" },
      { pokemonId: 748, name: "Toxapex" },
      { pokemonId: 908, name: "Meowscarada" },
    ],
  },
  {
    id: "t14",
    name: "Sand Balance",
    player: "Gabriel Agati",
    placement: "2nd Place",
    event: "Champions Europe Qualifier",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 478, name: "Froslass" },
    ],
  },
  {
    id: "t15",
    name: "Mega Gyarados Setup",
    player: "Jon Hu",
    placement: "Top 4",
    event: "Champions Showdown Week 2",
    pokemon: [
      { pokemonId: 130, name: "Gyarados" , isMega: true},
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 681, name: "Aegislash" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "t16",
    name: "Mega Scizor Pivot",
    player: "Rachel Annand",
    placement: "Top 4",
    event: "Champions Showdown Week 1",
    pokemon: [
      { pokemonId: 212, name: "Scizor" , isMega: true},
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 36, name: "Clefable" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
    ],
  },
  {
    id: "t17",
    name: "Greninja Offense",
    player: "Simone Sanvito",
    placement: "Top 8",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 376, name: "Metagross" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 130, name: "Gyarados" },
    ],
  },
  {
    id: "t18",
    name: "Glimmora Lead Offense",
    player: "Eric Rios",
    placement: "Top 8",
    event: "Champions Series Invitational #2",
    pokemon: [
      { pokemonId: 970, name: "Glimmora" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 478, name: "Froslass" },
    ],
  },
  {
    id: "t19",
    name: "Mega Altaria Fairy",
    player: "Tommy Cooleen",
    placement: "Top 8",
    event: "Champions Showdown Week 2",
    pokemon: [
      { pokemonId: 334, name: "Altaria" , isMega: true},
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 681, name: "Aegislash" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 908, name: "Meowscarada" },
    ],
  },
  {
    id: "t20",
    name: "Rain Semi-Room",
    player: "Luca Calore",
    placement: "Top 8",
    event: "Champions Europe Qualifier",
    pokemon: [
      { pokemonId: 186, name: "Politoed" },
      { pokemonId: 130, name: "Gyarados" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 478, name: "Froslass" },
    ],
  },
  {
    id: "t21",
    name: "Mega Houndoom Dark",
    player: "Marcus Wong",
    placement: "Top 8",
    event: "Champions Japan Qualifier",
    pokemon: [
      { pokemonId: 229, name: "Houndoom" , isMega: true},
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 282, name: "Gardevoir" },
    ],
  },
  {
    id: "t22",
    name: "Mega Heracross Trick Room",
    player: "Marco Silva",
    placement: "Top 8",
    event: "Champions Series Invitational #1",
    pokemon: [
      { pokemonId: 214, name: "Heracross" , isMega: true},
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 36, name: "Clefable" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "t23",
    name: "Mega Gengar Trap",
    player: "Yusei Aoki",
    placement: "2nd Place",
    event: "Champions Japan Qualifier",
    pokemon: [
      { pokemonId: 94, name: "Gengar" , isMega: true},
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 681, name: "Aegislash" },
    ],
  },
  {
    id: "t24",
    name: "Raichu Pin Offense",
    player: "Daniel Nolan",
    placement: "Top 4",
    event: "Champions Europe Qualifier",
    pokemon: [
      { pokemonId: 26, name: "Raichu" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t25",
    name: "Mega Absol Anti-Meta",
    player: "Flavio Del Pidio",
    placement: "Top 4",
    event: "Champions Korea Qualifier",
    pokemon: [
      { pokemonId: 359, name: "Absol" , isMega: true},
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 748, name: "Toxapex" },
    ],
  },
  {
    id: "t26",
    name: "Aurora Veil Offense",
    player: "Haruka Tanaka",
    placement: "1st Place",
    event: "Champions Snow Invitational",
    pokemon: [
      { pokemonId: 10103, name: "Alolan Ninetales" },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t27",
    name: "Electric Terrain Rush",
    player: "Jordan Blake",
    placement: "1st Place",
    event: "Champions Circuit Week 5",
    pokemon: [
      { pokemonId: 10100, name: "Alolan Raichu" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 887, name: "Dragapult" },
    ],
  },
  {
    id: "t28",
    name: "Rotom Control",
    player: "Sofia Chen",
    placement: "Top 4",
    event: "Champions Regionals Summer",
    pokemon: [
      { pokemonId: 10008, name: "Heat Rotom" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 376, name: "Metagross" },
    ],
  },
  {
    id: "t29",
    name: "Hisuian Chaos",
    player: "Kai Nakamura",
    placement: "2nd Place",
    event: "Champions Legends Cup",
    pokemon: [
      { pokemonId: 10340, name: "Hisuian Zoroark" },
      { pokemonId: 10336, name: "Hisuian Samurott" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 448, name: "Lucario" },
    ],
  },
  {
    id: "t30",
    name: "Decidueye Fighting Spirit",
    player: "Marcus Williams",
    placement: "1st Place",
    event: "Champions Open Series 4",
    pokemon: [
      { pokemonId: 10341, name: "Hisuian Decidueye" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 478, name: "Froslass" },
    ],
  },
  {
    id: "t31",
    name: "Mega Victreebel Sun",
    player: "Isabella Torres",
    placement: "Top 4",
    event: "Champions Latin Cup",
    pokemon: [
      { pokemonId: 71, name: "Victreebel" , isMega: true},
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t32",
    name: "Mega Steelix Sand",
    player: "Erik Johansson",
    placement: "2nd Place",
    event: "Champions Nordic Series",
    pokemon: [
      { pokemonId: 208, name: "Steelix" , isMega: true},
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 887, name: "Dragapult" },
    ],
  },
  {
    id: "t33",
    name: "Rotom Wash Balance",
    player: "Lisa Park",
    placement: "1st Place",
    event: "Champions Online Series 7",
    pokemon: [
      { pokemonId: 10009, name: "Wash Rotom" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "t34",
    name: "Mow Rotom Grass Core",
    player: "David Kim",
    placement: "Top 4",
    event: "Champions Pacific Qualifier",
    pokemon: [
      { pokemonId: 10012, name: "Mow Rotom" },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 376, name: "Metagross" },
    ],
  },
  {
    id: "t35",
    name: "Zoroark Illusion Tricks",
    player: "Nina Costa",
    placement: "1st Place",
    event: "Champions Showdown Week 8",
    pokemon: [
      { pokemonId: 10340, name: "Hisuian Zoroark" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "t36",
    name: "Fan Rotom Speed Control",
    player: "Tyler Adams",
    placement: "Top 8",
    event: "Champions US Nationals",
    pokemon: [
      { pokemonId: 10011, name: "Fan Rotom" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 350, name: "Milotic" },
    ],
  },
  {
    id: "t37",
    name: "Frost Rotom Hail Hybrid",
    player: "Yuki Sato",
    placement: "2nd Place",
    event: "Champions Japan Qualifier",
    pokemon: [
      { pokemonId: 10010, name: "Frost Rotom" },
      { pokemonId: 10103, name: "Alolan Ninetales" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 376, name: "Metagross" },
      { pokemonId: 282, name: "Gardevoir" },
    ],
  },
  {
    id: "t38",
    name: "Samurott Edge Setter",
    player: "Carlos Mendez",
    placement: "1st Place",
    event: "Champions Latin Invitational",
    pokemon: [
      { pokemonId: 10336, name: "Hisuian Samurott" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // Engine-Generated Teams — sourced from 1M+ battle simulation data
  // ════════════════════════════════════════════════════════════════
  {
    id: "e1",
    name: "Mega Beedrill HO",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 15, name: "Beedrill" , isMega: true},
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e2",
    name: "Mega Pidgeot Tailwind",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 733, name: "Toucannon" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 184, name: "Azumarill" },
      { pokemonId: 730, name: "Primarina" },
      { pokemonId: 934, name: "Garganacl" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "e3",
    name: "Pikachu Light Screen",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 25, name: "Pikachu" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 681, name: "Aegislash" },
    ],
  },
  {
    id: "e4",
    name: "Ninetales Sun",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 38, name: "Ninetales" },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 389, name: "Torterra" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e5",
    name: "Arcanine Intimidate Balance",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 59, name: "Arcanine" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e6",
    name: "Mega Alakazam Offense",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 65, name: "Alakazam" , isMega: true},
      { pokemonId: 59, name: "Arcanine" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 697, name: "Tyrantrum" },
      { pokemonId: 282, name: "Gardevoir" },
    ],
  },
  {
    id: "e7",
    name: "Slowbro Trick Room",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 80, name: "Slowbro" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 937, name: "Ceruledge" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 707, name: "Klefki" },
      { pokemonId: 934, name: "Garganacl" },
    ],
  },
  {
    id: "e8",
    name: "Starmie Speed Control",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 121, name: "Starmie" },
      { pokemonId: 5059, name: "Arcanine-Hisui" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 302, name: "Sableye" },
    ],
  },
  {
    id: "e9",
    name: "Mega Pinsir HO",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 127, name: "Pinsir" , isMega: true},
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 914, name: "Quaquaval" },
      { pokemonId: 699, name: "Aurorus" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "e10",
    name: "Ditto Transform Cheese",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 132, name: "Ditto" },
      { pokemonId: 866, name: "Mr. Rime" },
      { pokemonId: 877, name: "Morpeko" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "e11",
    name: "Flareon Sun Attacker",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 136, name: "Flareon" },
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e12",
    name: "Snorlax Trick Room",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 143, name: "Snorlax" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 534, name: "Conkeldurr" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 36, name: "Clefable" },
      { pokemonId: 681, name: "Aegislash" },
    ],
  },
  {
    id: "e13",
    name: "Meganium Support",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 154, name: "Meganium" },
      { pokemonId: 866, name: "Mr. Rime" },
      { pokemonId: 968, name: "Orthworm" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 869, name: "Alcremie" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e14",
    name: "Feraligatr Rain Sweep",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 160, name: "Feraligatr" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 866, name: "Mr. Rime" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 445, name: "Garchomp" },
    ],
  },
  {
    id: "e15",
    name: "Mega Ampharos TR",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 181, name: "Ampharos" , isMega: true},
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 534, name: "Conkeldurr" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e16",
    name: "Azumarill Belly Drum",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 184, name: "Azumarill" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 707, name: "Klefki" },
      { pokemonId: 844, name: "Sandaconda" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e17",
    name: "Espeon Magic Bounce",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 196, name: "Espeon" },
      { pokemonId: 855, name: "Polteageist" },
      { pokemonId: 707, name: "Klefki" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "e18",
    name: "Umbreon Stall Balance",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 197, name: "Umbreon" },
      { pokemonId: 569, name: "Garbodor" },
      { pokemonId: 914, name: "Quaquaval" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 934, name: "Garganacl" },
    ],
  },
  {
    id: "e19",
    name: "Skarmory Iron Defense",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 227, name: "Skarmory" },
      { pokemonId: 199, name: "Slowking" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 937, name: "Ceruledge" },
    ],
  },
  {
    id: "e20",
    name: "Pelipper Rain Core",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 160, name: "Feraligatr" },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 569, name: "Garbodor" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e21",
    name: "Mega Aggron Tank",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 306, name: "Aggron" , isMega: true},
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 392, name: "Infernape" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 937, name: "Ceruledge" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e22",
    name: "Mega Medicham Power",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 475, name: "Gallade" },
      { pokemonId: 855, name: "Polteageist" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e23",
    name: "Mega Manectric Intimidate",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 135, name: "Jolteon" },
      { pokemonId: 877, name: "Morpeko" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 697, name: "Tyrantrum" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e24",
    name: "Mega Sharpedo HO",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 134, name: "Vaporeon" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 968, name: "Orthworm" },
      { pokemonId: 389, name: "Torterra" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e25",
    name: "Mega Camerupt TR",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 637, name: "Volcarona" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 142, name: "Aerodactyl" },
    ],
  },
  {
    id: "e26",
    name: "Mega Banette Prankster",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 442, name: "Spiritomb" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 618, name: "Stunfisk" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e27",
    name: "Mega Glalie Offense",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 752, name: "Araquanid" },
      { pokemonId: 877, name: "Morpeko" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "e28",
    name: "Empoleon Competitive",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 395, name: "Empoleon" },
      { pokemonId: 5157, name: "Typhlosion-Hisui" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 5059, name: "Arcanine-Hisui" },
    ],
  },
  {
    id: "e29",
    name: "Mega Lopunny HO",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 428, name: "Lopunny" , isMega: true},
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 752, name: "Araquanid" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "e30",
    name: "Spiritomb Trick Room",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 442, name: "Spiritomb" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 143, name: "Snorlax" },
    ],
  },
  {
    id: "e31",
    name: "Hippowdon Sand",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 450, name: "Hippowdon" },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 6080, name: "Slowbro-Galar" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 699, name: "Aurorus" },
    ],
  },
  {
    id: "e32",
    name: "Mega Abomasnow Hail",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 460, name: "Abomasnow" , isMega: true},
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 6618, name: "Stunfisk-Galar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e33",
    name: "Leafeon Sun Sweep",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 470, name: "Leafeon" },
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 6199, name: "Slowking-Galar" },
      { pokemonId: 392, name: "Infernape" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e34",
    name: "Glaceon Trick Room",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 471, name: "Glaceon" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 844, name: "Sandaconda" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 6618, name: "Stunfisk-Galar" },
      { pokemonId: 36, name: "Clefable" },
    ],
  },
  {
    id: "e35",
    name: "Mamoswine Lead Offense",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 461, name: "Weavile" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 637, name: "Volcarona" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e36",
    name: "Mega Gallade Offense",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 475, name: "Gallade" , isMega: true},
      { pokemonId: 157, name: "Typhlosion" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 534, name: "Conkeldurr" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e37",
    name: "Rotom-Base Versatile",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 479, name: "Rotom" },
      { pokemonId: 5059, name: "Arcanine-Hisui" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 730, name: "Primarina" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "e38",
    name: "Serperior Contrary",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 497, name: "Serperior" },
      { pokemonId: 392, name: "Infernape" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e39",
    name: "Emboar Trick Room",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 500, name: "Emboar" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 869, name: "Alcremie" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e40",
    name: "Samurott Rain Attacker",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 503, name: "Samurott" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 6618, name: "Stunfisk-Galar" },
      { pokemonId: 637, name: "Volcarona" },
      { pokemonId: 697, name: "Tyrantrum" },
      { pokemonId: 869, name: "Alcremie" },
    ],
  },
  {
    id: "e41",
    name: "Krookodile Intimidate",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 553, name: "Krookodile" },
      { pokemonId: 914, name: "Quaquaval" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e42",
    name: "Zoroark Illusion Mindgames",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 571, name: "Zoroark" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 697, name: "Tyrantrum" },
      { pokemonId: 666, name: "Vivillon" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 302, name: "Sableye" },
    ],
  },
  {
    id: "e43",
    name: "Emolga Support",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 587, name: "Emolga" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 699, name: "Aurorus" },
      { pokemonId: 730, name: "Primarina" },
      { pokemonId: 914, name: "Quaquaval" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "e44",
    name: "Golurk Trick Room",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 623, name: "Golurk" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 937, name: "Ceruledge" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e45",
    name: "Hydreigon Special Offense",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 635, name: "Hydreigon" },
      { pokemonId: 618, name: "Stunfisk" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 752, name: "Araquanid" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e46",
    name: "Chesnaught Tank",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 652, name: "Chesnaught" },
      { pokemonId: 389, name: "Torterra" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 157, name: "Typhlosion" },
      { pokemonId: 282, name: "Gardevoir" },
    ],
  },
  {
    id: "e47",
    name: "Delphox Trick Room",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 655, name: "Delphox" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e48",
    name: "Diggersby Band",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 660, name: "Diggersby" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 534, name: "Conkeldurr" },
      { pokemonId: 569, name: "Garbodor" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e49",
    name: "Talonflame Tailwind HO",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 663, name: "Talonflame" },
      { pokemonId: 5059, name: "Arcanine-Hisui" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 877, name: "Morpeko" },
      { pokemonId: 666, name: "Vivillon" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "e50",
    name: "Floette Support",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 199, name: "Slowking" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e51",
    name: "Furfrou Fur Coat",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 676, name: "Furfrou" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 697, name: "Tyrantrum" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e52",
    name: "Meowstic Prankster",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 678, name: "Meowstic" },
      { pokemonId: 869, name: "Alcremie" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "e53",
    name: "Clawitzer Mega Launcher",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 693, name: "Clawitzer" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 6199, name: "Slowking-Galar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 858, name: "Hatterene" },
    ],
  },
  {
    id: "e54",
    name: "Sylveon Hyper Voice",
    player: "Engine Analysis",
    placement: "1st Place",
    event: "1M Battle Simulation — Top Performer",
    pokemon: [
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 914, name: "Quaquaval" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e55",
    name: "Hawlucha Unburden",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 701, name: "Hawlucha" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 534, name: "Conkeldurr" },
      { pokemonId: 730, name: "Primarina" },
      { pokemonId: 877, name: "Morpeko" },
    ],
  },
  {
    id: "e56",
    name: "Goodra Assault Vest",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 635, name: "Hydreigon" },
      { pokemonId: 844, name: "Sandaconda" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e57",
    name: "Trevenant Trick Room",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 711, name: "Gourgeist" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e58",
    name: "Avalugg Trick Room Tank",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — Niche Pick",
    pokemon: [
      { pokemonId: 584, name: "Vanilluxe" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 707, name: "Klefki" },
      { pokemonId: 866, name: "Mr. Rime" },
    ],
  },
  {
    id: "e59",
    name: "Noivern Tailwind",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 715, name: "Noivern" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 855, name: "Polteageist" },
      { pokemonId: 937, name: "Ceruledge" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 658, name: "Greninja" },
    ],
  },
  {
    id: "e60",
    name: "Decidueye Ghost Offense",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 724, name: "Decidueye" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 866, name: "Mr. Rime" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e61",
    name: "Lycanroc Sand Rush",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 745, name: "Lycanroc" },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 877, name: "Morpeko" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 855, name: "Polteageist" },
    ],
  },
  {
    id: "e62",
    name: "Mudsdale Trick Room",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 750, name: "Mudsdale" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 968, name: "Orthworm" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e63",
    name: "Tsareena Queenly Majesty",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 763, name: "Tsareena" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 699, name: "Aurorus" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e64",
    name: "Mimikyu Disguise Offense",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 778, name: "Mimikyu" },
      { pokemonId: 6618, name: "Stunfisk-Galar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 637, name: "Volcarona" },
      { pokemonId: 937, name: "Ceruledge" },
      { pokemonId: 302, name: "Sableye" },
    ],
  },
  {
    id: "e65",
    name: "Kommo-o Clangorous Soul",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 784, name: "Kommo-o" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 389, name: "Torterra" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e66",
    name: "Corviknight Bulk Up",
    player: "Engine Analysis",
    placement: "1st Place",
    event: "1M Battle Simulation — Top Performer",
    pokemon: [
      { pokemonId: 823, name: "Corviknight" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 844, name: "Sandaconda" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e67",
    name: "Grimmsnarl Screens",
    player: "Engine Analysis",
    placement: "1st Place",
    event: "1M Battle Simulation — Top Performer",
    pokemon: [
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 569, name: "Garbodor" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 887, name: "Dragapult" },
    ],
  },
  {
    id: "e68",
    name: "Runerigus Trick Room",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 867, name: "Runerigus" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 157, name: "Typhlosion" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e69",
    name: "Kleavor Lead Offense",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 900, name: "Kleavor" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 752, name: "Araquanid" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e70",
    name: "Ursaluna Trick Room Beatdown",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 901, name: "Ursaluna" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e71",
    name: "Basculegion Rain Attacker",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 902, name: "Basculegion" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 5157, name: "Typhlosion-Hisui" },
      { pokemonId: 968, name: "Orthworm" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e72",
    name: "Sneasler Poison Touch",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 392, name: "Infernape" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e73",
    name: "Pawmot Volt Absorb",
    player: "Engine Analysis",
    placement: "Top 8",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 923, name: "Pawmot" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e74",
    name: "Maushold Population Bomb",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 925, name: "Maushold" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 730, name: "Primarina" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e75",
    name: "Garganacl Salt Cure Stall",
    player: "Engine Analysis",
    placement: "1st Place",
    event: "1M Battle Simulation — Top Performer",
    pokemon: [
      { pokemonId: 934, name: "Garganacl" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e76",
    name: "Armarouge Trick Room",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 936, name: "Armarouge" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e77",
    name: "Tinkaton Mold Breaker",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 959, name: "Tinkaton" },
      { pokemonId: 6080, name: "Slowbro-Galar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 823, name: "Corviknight" },
    ],
  },
  {
    id: "e78",
    name: "Palafin Zero to Hero",
    player: "Engine Analysis",
    placement: "1st Place",
    event: "1M Battle Simulation — Top Performer",
    pokemon: [
      { pokemonId: 964, name: "Palafin" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e79",
    name: "Tatsugiri Dondozo Core",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 978, name: "Tatsugiri" },
      { pokemonId: 977, name: "Dondozo" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e80",
    name: "Farigiraf Armor Tail",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e81",
    name: "Sinistcha Hospitality",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 700, name: "Sylveon" },
    ],
  },
  {
    id: "e82",
    name: "Archaludon Steel Offense",
    player: "Engine Analysis",
    placement: "1st Place",
    event: "1M Battle Simulation — Top Performer",
    pokemon: [
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e83",
    name: "Hydrapple Trick Room",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 1019, name: "Hydrapple" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 700, name: "Sylveon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
  },
  {
    id: "e84",
    name: "Volcarona Sun",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 637, name: "Volcarona" },
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 389, name: "Torterra" },
      { pokemonId: 302, name: "Sableye" },
      { pokemonId: 980, name: "Clodsire" },
    ],
  },
  {
    id: "e85",
    name: "Aerodactyl HO",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 392, name: "Infernape" },
      { pokemonId: 887, name: "Dragapult" },
      { pokemonId: 534, name: "Conkeldurr" },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 184, name: "Azumarill" },
    ],
  },
  {
    id: "e86",
    name: "Primarina Trick Room",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 730, name: "Primarina" },
      { pokemonId: 858, name: "Hatterene" },
      { pokemonId: 752, name: "Araquanid" },
      { pokemonId: 464, name: "Rhyperior" },
      { pokemonId: 569, name: "Garbodor" },
      { pokemonId: 199, name: "Slowking" },
    ],
  },
  {
    id: "e87",
    name: "Ceruledge Offense",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 937, name: "Ceruledge" },
      { pokemonId: 914, name: "Quaquaval" },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 450, name: "Hippowdon" },
      { pokemonId: 697, name: "Tyrantrum" },
      { pokemonId: 707, name: "Klefki" },
    ],
  },
  {
    id: "e88",
    name: "Hisuian Typhlosion Ghost",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 5157, name: "Typhlosion-Hisui" },
      { pokemonId: 157, name: "Typhlosion" },
      { pokemonId: 877, name: "Morpeko" },
      { pokemonId: 376, name: "Metagross" },
      { pokemonId: 448, name: "Lucario" },
      { pokemonId: 6199, name: "Slowking-Galar" },
    ],
  },
  {
    id: "e89",
    name: "Hisuian Arcanine Balance",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 5059, name: "Arcanine-Hisui" },
      { pokemonId: 869, name: "Alcremie" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 968, name: "Orthworm" },
      { pokemonId: 748, name: "Toxapex" },
      { pokemonId: 855, name: "Polteageist" },
    ],
  },
  {
    id: "e90",
    name: "Aurorus Hail",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 699, name: "Aurorus" },
      { pokemonId: 460, name: "Abomasnow" },
      { pokemonId: 866, name: "Mr. Rime" },
      { pokemonId: 844, name: "Sandaconda" },
      { pokemonId: 80, name: "Slowbro" },
      { pokemonId: 6080, name: "Slowbro-Galar" },
    ],
  },
  {
    id: "e91",
    name: "Vivillon Compound Eyes",
    player: "Engine Analysis",
    placement: "Top Cut",
    event: "1M Battle Simulation — High ELO",
    pokemon: [
      { pokemonId: 666, name: "Vivillon" },
      { pokemonId: 6618, name: "Stunfisk-Galar" },
      { pokemonId: 618, name: "Stunfisk" },
      { pokemonId: 765, name: "Oranguru" },
      { pokemonId: 901, name: "Ursaluna" },
      { pokemonId: 143, name: "Snorlax" },
    ],
  },
];

/**
 * Lookup: returns all winning teams that include a given Pokémon ID.
 */
export function getTeamsForPokemon(pokemonId: number): WinningTeam[] {
  return WINNING_TEAMS.filter((team) =>
    team.pokemon.some((p) => p.pokemonId === pokemonId)
  );
}
